"use client";

import { useState } from "react";
import { HardDrive } from "lucide-react";

const TABS = ["All", "Video", "Images", "Audio"];

export default function AssetsPage() {
  const [tab, setTab] = useState("All");
  const [sort, setSort] = useState("Newest");
  const assets: never[] = [];

  return (
    <div className="flex flex-col flex-1">
      <main className="flex-1 p-6">
        {/* Tab bar + controls */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex gap-1 bg-gray-100 rounded-lg p-1">
            {TABS.map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${
                  tab === t ? "bg-white shadow text-[#111827]" : "text-[#6B7280] hover:text-[#111827]"
                }`}
              >
                {t}
              </button>
            ))}
          </div>
          <div className="flex gap-2">
            <input
              placeholder="Search assets..."
              className="px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none w-48"
            />
            <select
              value={sort}
              onChange={(e) => setSort(e.target.value)}
              className="px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none"
            >
              {["Newest", "Oldest", "Largest", "Smallest"].map((o) => <option key={o}>{o}</option>)}
            </select>
          </div>
        </div>

        {assets.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-32 text-[#6B7280]">
            <HardDrive size={56} className="mb-4 opacity-20" />
            <p className="font-semibold text-lg">No assets yet</p>
            <p className="text-sm mt-1">Assets generated by the agent will appear here</p>
          </div>
        ) : (
          <div className="grid grid-cols-5 gap-4">
            {assets.map((_, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-200 p-3 hover:shadow-md transition-shadow">
                <div className="bg-gray-100 aspect-video rounded-lg mb-2" />
                <p className="text-sm font-medium text-[#111827] truncate">asset-{i}.mp4</p>
                <p className="text-xs text-[#6B7280]">0 MB · Just now</p>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
